variables:
  GCP_PROJECT_ID: $GCP_PROJECT_ID
  IMAGE_NAME: $IMAGE_NAME
  CLUSTER: $CLUSTER
  CLUSTER_ZONE: $CLUSTER_ZONE

services:
  - docker:dind

stages:
  - publish
  - deploy

publish-image:
  stage: publish
  image: dwdraju/alpine-gcloud
  script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud container builds submit . --config=cloudbuild.yaml --substitutions BRANCH_NAME=$CI_COMMIT_REF_NAME,_IMAGE_NAME=$IMAGE_NAME
  only:
    - branches

deploy-image:
  stage: deploy
  image: dwdraju/gke-kubectl-docker
  script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud container clusters get-credentials $CLUSTER --zone $CLUSTER_ZONE
    - kubectl set env deployment/dev-auth CI_COMMIT_SHA=$CI_COMMIT_SHA
    - kubectl set image deployment/dev-auth dev-auth=gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_REF_NAME
  only:
    - docker
