version: '2'
services:
  msa-auth:
    image: node:9
    container_name: msa-auth
    #build: .
    volumes:
      - ./:/app/
      - .env:/app/.env
    ports:
      - "8001"
    entrypoint: /bin/sh
    command: -c "sleep 5 && cd /app/ && yarn && yarn start:dev"
    networks:
      - evolve
networks:
  evolve:
    external: true
